### ISSUE TITLE
System optionally uses Elasticsearch to serve job search requests

### ISSUE THREAD

**Issue by amitsharma1981** [Netflix/genie#137] opened 2015-06-04 22:49 UTC
The GET jobs query even without any filters gets pretty slow as the tags table grows. Need to optimize it.

**Comment by harakiro** [comment] 2016-07-09 03:46
At least with Genie 2.x and mysql we've discovered the issue is with mysql. While the query generated for selecting clusters with multiple tags is horrible in terms of efficient, the DB should handle it better. We changed to postgres, and or queries went from minutes, down to sub-second response times.

**Comment by tgianos** [comment] 2016-07-15 22:05
@harakiro that's interesting. Do you have any insight into why that is? Genie 3 has scripts for both mysql and postgres. We use MySQL internally cause a lot of monitoring tools exist for it so we haven't really explored postgres much.

**Comment by tgianos** [comment] 2016-10-20 21:04
closing this. Will re-evaluate later. Genie 3 has a lot of improvements to search and database design that lowers the need for this significantly.

**Closed by tgianos** 2016-10-20 21:04 UTC
Labels: feature
