### ISSUE TITLE
Errors after upgrading jar from 3.0.8 to 3.2.3

### ISSUE THREAD

**Issue by kirubel** [Netflix/genie#636] opened 2017-11-06 20:01 UTC
Getting the following errors after upgrading .jar from 3.0.8 to 3.2.3.  The DB was upgraded to 3.2.0 Postgres.  The UI /jobs is populated but not /clusters or /applications.
Below is entry from the error logs

" WARN 45466 --- [nio-8080-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 22003
2017-11-02 19:22:56.199 ERROR 45466 --- [nio-8080-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : Bad value for type long : Analytics Runtime Framework SIT/Andromeda Submit Command
2017-11-02 19:22:56.206 ERROR 45466 --- [nio-8080-exec-8] c.n.g.w.c.GenieExceptionMapper           : Failed to execute data service method
"
 looks like some data type mismatch between existing data and Spring Hibernate.

Any advice would be appreciated!

**Comment by tgianos** [comment] 2017-11-06 20:21
Hey @kirubel To verify your upgrade process you were on the postgres schema from 3.0.1?

And then you ran the following files to upgrade:
[3.0.1 to 3.1.0](https://github.com/Netflix/genie/blob/3.2.x/genie-ddl/src/main/sql/postgresql/upgrade-3.0.1-to-3.1.0.postgresql.sql)
[3.1.x to 3.2.0](https://github.com/Netflix/genie/blob/3.2.x/genie-ddl/src/main/sql/postgresql/upgrade-3.1.x-to-3.2.0.postgresql.sql)

Is this true?

**Comment by tgianos** [comment] 2017-11-06 20:31
can you run `pg_dump` on your database with the following flags:
`pg_dump --no-tablespaces --no-owner --no-privileges --schema-only` and `diff` it to the [expected schema](https://raw.githubusercontent.com/Netflix/genie/v3.2.3/genie-ddl/src/main/sql/postgresql/schema.postgresql.sql) and post any results?

I believe @mprimi tested all this as he was doing the 3.2.x changes but we may have missed something as Postgresql isn't our current production DB

**Comment by kirubel** [comment] 2017-11-06 23:44
Here are some difference
1) - Dumped from database version 9.6.2
6.	-- Dumped by pg_dump version 9.6.5	6.	-- Dumped by pg_dump version 9.6.4
(output from my env was 9.6.2 for server and 9.6.4 for client node

The following lines were present in my env but missing from the expected schema.
****************1st diff******************************
- "--
		283.	-- Name: schema_version; Type: TABLE; Schema: public; Owner: -
		284.	--
		285.	
		286.	CREATE TABLE schema_version (
		287.	    version_rank integer NOT NULL,
		288.	    installed_rank integer NOT NULL,
		289.	    version character varying(50) NOT NULL,
		290.	    description character varying(200) NOT NULL,
		291.	    type character varying(20) NOT NULL,
		292.	    script character varying(1000) NOT NULL,
		293.	    checksum integer,
		294.	    installed_by character varying(100) NOT NULL,
		295.	    installed_on timestamp without time zone DEFAULT now() NOT NULL,
		296.	    execution_time integer NOT NULL,
		297.	    success boolean NOT NULL"
**************2nd**************************************
-- Name: schema_version schema_version_pk; Type: CONSTRAINT; Schema: public; Owner: -
		431.	--
		432.	
		433.	ALTER TABLE ONLY schema_version
		434.	    ADD CONSTRAINT schema_version_pk PRIMARY KEY (version);
		435.	
		436.	
		437.	--
********************3rd diff*************************
-- Name: schema_version_ir_idx; Type: INDEX; Schema: public; Owner: -
		684.	--
		685.	
		686.	CREATE INDEX schema_version_ir_idx ON schema_version USING btree (installed_rank);
		687.	
		688.	
		689.	--
		690.	-- Name: schema_version_s_idx; Type: INDEX; Schema: public; Owner: -
		691.	--
		692.	
		693.	CREATE INDEX schema_version_s_idx ON schema_version USING btree (success);
		694.	
		695.	
		696.	--
		697.	-- Name: schema_version_vr_idx; Type: INDEX; Schema: public; Owner: -
		698.	--
		699.	
		700.	CREATE INDEX schema_version_vr_idx ON schema_version USING btree (version_rank);
		701.	
		702.	
		703.	--
***********5th diff********************
These lines ",
		240.	    configs text DEFAULT ''::character varying NOT NULL"
came after the line "memory integer,
239.	    applications character varying(2048) DEFAULT '[]'::character varying NOT NULL,	238.	    applications character varying(2048) DEFAULT '[]'::character varying NOT NULL,"
but in the schema you provided the line "configs text DEFAULT ''::character varying NOT NULL," comes after the line "dependencies text DEFAULT ''::character varying NOT NULL,"

**Comment by mprimi** [comment] 2017-11-06 23:49
Hello @kirubel, let me try to:
1. Run all integration tests against PG with a fresh 3.2.0 database
2. Retry the upgrade from 3.0.x to 3.2.x schema.

I'll get back to you in a bit.

**Comment by kirubel** [comment] 2017-11-07 01:21
@mprimi Thank you!

**Comment by mprimi** [comment] 2017-11-08 16:15
@kirubel I tried to perform all upgrades from 3.0.x to 3.2.x and compare against fresh created schemas. (e.g. compare 3.1.x upgraded to 3.2.x against fresh 3.2.x).
Dumps attached: [schema-dumps.zip](https://github.com/Netflix/genie/files/1454554/schema-dumps.zip)

The only difference I'm seeing is order the `configs` column in the `job_requests` table in 3.1.x (fresh vs upgraded from 3.0.x) which you mentioned as difference number 5. 
But the order of that column should not create any issue.

Can you post any more info you have, such as the full exception trace, raw database schema dumps, etc?

**Comment by mprimi** [comment] 2017-11-09 22:09
@kirubel Still trying to reproduce your problem, but actually bumped into something interesting.
The schema migration from 3.0.1 -> 3.1.0 -> 3.2.0 seems to work if the database is empty (as per previous comment).
However if the database is not empty it seems to fail. I can reproduce as follows:

 * Create a `genie` database with 3.0.1 schema using PostgreSQL 9.6
 * Start an instance of Genie server configure to use the above database
 * use the API to create some clusters/apps/commands, schedule a couple of jobs to check everything is ok
 * Shut down the server
 * Perform 3.0.1 -> 3.1.0 schema migration
 * Perform 3.1.0 -> 3.2.0 schema migration

The last step **fails**: 
```
ERROR:  multiple primary keys for table "application_configs" are not allowed
SQL state: 42P16
```
Is it possible this step failed for you too, and the errors you're seeing now are result of this botched migration?

**Comment by mprimi** [comment] 2017-11-09 23:53
After manually fixing the upgrade script (not 100% sure this is the proper way), I can perform the 3.1.0 -> 3.2.0 upgrade.
However once I start the 3.2.x server, there are migration error from Flyway, and the data in the database is **wiped**.
Not great, will have to see about this with @tgianos.

**Comment by kirubel** [comment] 2017-11-10 02:48
The database was showing blank when using v3.2.3 but all data was present again when we reverted back the jar back to v3.0.8.  Maybe the DB never upgraded due to error you mentioned.  I will double check if the dB got upgraded or not and update you.  Thanks !

**Comment by mprimi** [comment] 2017-11-10 23:57
I think the problem is the following:
In 3.1 we moved some fields from `varchar` to `text` (https://github.com/Netflix/genie/pull/558).
Some field entities were marked `@Lob` to reflect this.
With HSQL and MySQL this seems to work ok.

With PostgreSQL/Hibernate however, the connector expects a long (a pointer to a blob containing the data) and it finds some text instead, so it errors out.
In more detail: https://shred.zone/cilla/page/299/string-lobs-on-postgresql-with-hibernate-36.html

We're going to patch this.

**Comment by kirubel** [comment] 2017-11-11 04:00
Oh okay! Thank you!

**Comment by mprimi** [comment] 2017-11-14 01:17
@kirubel I just released 3.1.3 which should fix this problem, could you confirm by doing the following:

* Start with your 3.0.1 schema with data
* Run the database upgrade to 3.1.0
* Run server version 3.1.3

The App/Cluster/Commands page should no longer show the error you initially reported.

Before you can upgrade to 3.2.x, we need to release 3.2.5 which I hope to do soon. However if in the meantime you could test the fix is working for 3.1.x, that would be great.

These are the relevant changes:
3.1.x: https://github.com/Netflix/genie/pull/641
3.2.x: https://github.com/Netflix/genie/pull/642
More testing: https://github.com/Netflix/genie/pull/639

**Comment by mprimi** [comment] 2017-11-16 00:14
@kirubel after confirming 3.0.x to 3.1.x is working, you can now update to 3.2.x (3.2.5 or newer).
Notice that the [3.1 to 3.2 PostgreSQL upgrade script](https://github.com/Netflix/genie/blob/3.2.x/genie-ddl/src/main/sql/postgresql/upgrade-3.1.x-to-3.2.0.postgresql.sql) is different from the one you previously applied, make sure to use the latest.
Let us know if you run into any trouble.

**Comment by kirubel** [comment] 2017-11-16 05:18
Thank you very much.  I will work on applying the new updates and will let
you know of the results!

**Comment by tgianos** [comment] 2017-12-11 20:35
@kirubel have you have any problems? We'd like to close this issue if it is resolved

**Comment by kirubel** [comment] 2017-12-14 20:14
hi Tom, apologies, we haven't been able to retest the issue in the
environment due to scheduled releases that have been going on the past few
weeks.  But I will update you as soon as we test it.  If you need to close
it now, maybe we can reopen it later if the problem persists.

**Closed** 2018-04-20 18:52 UTC
Labels: question
